import Head from 'next/head'
// import Image from 'next/image'
import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'
import { FormControl, TextField } from '@mui/material'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <h1>Enter your info</h1>
          <FormControl sx={{ width: '25ch' }}>
            <TextField
              id="first-name"
              label="First Name"
              variant="outlined"
            />
            <TextField
              id="last-name"
              label="Last Name"
              variant="outlined"
            />
            <TextField
              id="phone"
              label="Phone" 
              variant="outlined"
              inputProps={{ inputMode: 'numeric', pattern: '[0-9]*' }}
            />
            <TextField
              id="email"
              label="Email"
              variant="outlined"
            />
          </FormControl>
        </div>
        <div>
          <h1>What state do you currently reside in?</h1>
          <FormControl sx={{ width: '25ch' }}>
            <TextField
              id="State"
              label="State"
              variant="outlined"
            />
          </FormControl>
        </div>
        
        <div>
          <h1>What University would you like to attend?</h1> 
          <FormControl sx={{ width: '25ch' }}>
            <TextField
              id="State"
              label="State"
              variant="outlined"
            />
          </FormControl>
        </div>
      </main>
    </>
  )
}
